Removed MPEG-1 Audio Layer II bitrate limitation.
Now uses POSIX bourne shell, not GNU bash.

Uses bc co-process for arithmetic (POSIX expr command also only
deals with integers, like Bourne Shell arithmetic).

Improved code maintainability with constant declarations.

diff --git a/divxhtcheck b/divxhtcheck
--- a/divxhtcheck
+++ b/divxhtcheck
@@ -1,6 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 # divxhtcheck: Runs a series of quality-assurance tests on a DivX AVI
-#   file to ensure that it complies with the DivX Home Theatre profile. 
+#   file to ensure that it complies with the DivX Home Theatre profile.
 # Copyright (C) 2012 Bryan Rodgers <rodgersb@it.net.au>
 #
 # This program is free software: you can redistribute it and/or modify
@@ -15,6 +15,61 @@
 #
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
+#
+# Note that you'll need the following installed on your system to run
+# this script:
+#   * MPlayer <http://mplayerhq.hu/>
+#   * A POSIX-compatible bc implementation (GNU bc is also good)
+#   * GNU coreutils <http://www.gnu.org/software/coreutils/>
+#       (for the `mkfifo' command needed to create named pipes)
+
+# Name of this script, used for displaying error messages.
+PROGNAME="${0##*/}"
+
+# List of MPlayer audio format codes for the ID_AUDIO_FORMAT variable
+# returned by `mplayer -identify'.
+AUDF_MPEG1_LAYER_II=80      # MPEG-1 Layer II
+AUDF_MPEG1_LAYER_III=85     # MPEG-1 Layer III
+AUDF_DOLBY_AC3=8192         # Dolby AC-3
+# Codec string MPlayer uses to identify DIVX v3 video streams
+VIDCODEC_DIVX3=ffdivx
+# Codec string MPlayer uses to identify DIVX v5 video streams
+VIDCODEC_DIVX5=ffodivx
+
+# Warning message fragment that MPlayer produces if it plays a DivX
+# video stream with non-standard bi-directional predictive frames (i.e.
+# B-frames). The search string may need to be updated if the message
+# changes. The below message is current for MPlayer 1.0rc4.
+MPLAYER_WARN_BFRAMES_TEXT="Invalid and inefficient vfw-avi packed B frames detected"
+
+# When testing under the GNU system this is needed to help ensure that
+# this script will work under more strict POSIX-compliant systems (e.g.
+# commercial UNIXes).
+export POSIXLY_CORRECT=1
+
+print_help()
+{
+    cat <<EOF
+Usage: $PROGNAME AVIFILE..."
+Checks a list of AVI files for DivX Home Theatre compliance.
+EOF
+}
+
+print_try_help()
+{
+    echo "Try \`$PROGNAME -h' for more information." >&2
+}
+
+assert_have_program()
+{
+    local prog
+    for prog in $*; do
+        if ! which $prog >/dev/null 2>&1; then
+            echo "$PROGNAME: error: program \`$prog' is needed in the system path to run this script." >&2
+            exit 1
+        fi
+    done
+}
 
 # $1 = video file name
 # Returns zero exit status if success; non-zero if failure.
@@ -31,16 +86,16 @@
 #   ID_VIDEO_BITRATE: Bitrate of video stream, in bits per second (integer).
 #   ID_VIDEO_WIDTH: Pixel width of video stream.
 #   ID_VIDEO_HEIGHT: Pixel height of video stream.
-#   ID_VIDEO_FPS: 
+#   ID_VIDEO_FPS:
 #       Frame rate (frames per second) of video stream, in decimal. May
 #       be zero for certain container formats that have variable frame
 #       rates (frames are indexed by millisecond-resolution timestamps
 #       instead), such as WMV, ASF and MPEG-4.
 #   ID_VIDEO_ASPECT: Aspect ratio (width/height) expressed as decimal.
 #       In some cases this may be zero (if it's not recorded anywhere in the file).
-#   ID_VIDEO_CODEC: Codec MPlayer has selected to decode video stream 
+#   ID_VIDEO_CODEC: Codec MPlayer has selected to decode video stream
 #       (should use "ffodivx" for DivX 5, "ffdivx" for DivX 3)
-#   ID_AUDIO_FORMAT: 
+#   ID_AUDIO_FORMAT:
 #       An integer (internal to MPlayer) describing the audio stream format:
 #           80      MPEG-1 Layer II audio (aka "mp2")
 #           85      MPEG-1 Layer III audio (aka "mp3")
@@ -58,38 +113,108 @@
 #       "QUIT": User manually exited.
 #       "ERROR": Error occurred (e.g. format unrecognised)
 #       "NONE": Cause unknown.
-mplayer_identify() {
+mplayer_identify()
+{
     unset ID_EXIT
     if ! [ -e "$1" ]; then
-        echo "error: cannot find file \`$1'" >&2
+        echo "$PROGNAME: error: cannot find file \`$1'" >&2
         return 1
     elif ! [ -f "$1" ]; then
-        echo "error: \`$1' is not a file" >&2
+        echo "$PROGNAME: error: \`$1' is not a file" >&2
         return 1
     fi
-    eval `mplayer -identify -really-quiet -vo null -ao null -frames 0 "$1" 2>/dev/null \
-        | { while read line; do printf '%q\n' "$line"; done; }`
+    # Note: the aspect ratio does not become available until we play at least 1 frame
+    eval `mplayer -noconfig all -cache-min 0 -identify -really-quiet -vo null -ao null -frames 1 "$1" 2>/dev/null \
+        | sed '/^\w\+=/!d; s/\([^-[:alnum:]=_.:/+@,^]\)/\\\\\1/g'`
     if [ "$ID_EXIT" != EOF ]; then
-        echo "error: unable to retrieve information for file \`$1'" >&2
+        echo "$PROGNAME: error: unable to retrieve information for file \`$1'" >&2
         return 1
     fi
+}
+
+# Template used for temporary files
+MKTEMP_TEMPLATE=/tmp/divxhtcheck.XXXXXX
+# Named pipe used to send statements to POSIX bc co-process
+BC_STMT_PIPE=
+# Named pipe used to read results back from POSIX bc co-process
+BC_RSLT_PIPE=
+# PID of bc co-process (in case it needs to be killed)
+BC_PID=
+
+# Starts a background POSIX bc co-process that can receive input and
+# return output via the file descriptors 4 and 5 respectively.
+# Terminates the script with an error message if the bc program cannot
+# be launched in this manner.
+bc_start()
+{
+    if ! BC_STMT_PIPE=`mktemp $MKTEMP_TEMPLATE`; then
+        echo "$PROGNAME: error: unable to create temporary file \`$MKTEMP_TEMPLATE'" >&2
+        exit 1
+    elif ! BC_RSLT_PIPE=`mktemp $MKTEMP_TEMPLATE`; then
+        echo "$PROGNAME: error: unable to create temporary file \`$MKTEMP_TEMPLATE'" >&2
+        exit 1
+    fi
+    rm -f $BC_STMT_PIPE $BC_RSLT_PIPE
+    if ! mkfifo -m600 $BC_STMT_PIPE $BC_RSLT_PIPE; then
+        echo "$PROGNAME: error: unable to create temporary named pipes" >&2
+        exit 1
+    fi
+    bc -q <$BC_STMT_PIPE >$BC_RSLT_PIPE &
+    BC_PID=$!
+    if ! exec 4>$BC_STMT_PIPE 5<$BC_RSLT_PIPE; then
+        echo "$PROGNAME: error: unable to communicate with \`bc' child process" >&2
+        exit 1
+    fi
+    rm -f $BC_STMT_PIPE $BC_RSLT_PIPE
+}
+
+# Sends a line of input asynchronously to the POSIX bc co-process. Each
+# argument is sent as an individual line. Any results that these
+# statements might produce can be read back through bc_read_result.
+bc_run_cmds()
+{
+    local arg
+    for arg; do
+        echo "$arg" >&4
+    done
+}
+
+# Reads back one or more lines of output from the POSIX bc co-process.
+# Each argument contains the name of a shell variable that successive
+# lines read back will be stored in. Be careful not to specify more
+# arguments than there are lines pending, otherwise deadlock will occur.
+bc_read_result()
+{
+    local arg
+    for arg; do
+        read $arg <&5
+    done
+}
+
+# Terminates the POSIX bc co-process.
+bc_end()
+{
+    exec 4>&- 5<&-
+    wait $BC_PID
 }
 
 # Tests if a file is DivX Home Theatre compliant
 # $1 = file to test
 # Returns zero exit status if compliant; non-zero otherwise.
 # Messages will be printed to standard error explaining any failures.
-divxht_test() {
-    let failed=0
-    
+divxht_test()
+{
+    local failed
+    failed=0
+
     # Confirm AVI file extension
     if [ `expr match "$1" '.*\.[Aa][Vv][Ii]$'` -eq 0 ]; then
-        echo "failure: \`$1' does not have file extension \`.avi'" >&2
+        echo "$PROGNAME: failure: \`$1' does not have file extension \`.avi'" >&2
         return 1
     fi
 
     if [ `expr match "${1##*/}" '.*\.[Aa][Vv][Ii]$'` -gt 60 ]; then
-        echo "failure: \`$1' file name is longer than 64 characters" >&2
+        echo "$PROGNAME: failure: \`$1' file name is longer than 64 characters" >&2
         return 1
     fi
 
@@ -99,107 +224,97 @@ divxht_test() {
 
     # Confirm AVI container
     if [ "$ID_DEMUXER" != avi ]; then
-        echo "failure: \`$1' is not in avi container format: $ID_DEMUXER" >&2
-        let failed=1
+        echo "$PROGNAME: failure: \`$1' is not in avi container format: $ID_DEMUXER" >&2
+        failed=1
     fi
-    
+
     # Confirm video FourCC is "DX50", "DIVX", "XVID" or "DIV3"
     if [ "$ID_VIDEO_FORMAT" != DX50 \
         -a "$ID_VIDEO_FORMAT" != DIVX \
         -a "$ID_VIDEO_FORMAT" != XVID \
         -a "$ID_VIDEO_FORMAT" != DIV3 ]; then
-        echo "failure: \`$1' video fourcc is not \`DX50', \`DIVX', \`XVID' or \`DIV3': $ID_VIDEO_FORMAT" >&2
-        let failed=1
+        echo "$PROGNAME: failure: \`$1' video fourcc is not \`DX50', \`DIVX', \`XVID' or \`DIV3': $ID_VIDEO_FORMAT" >&2
+        failed=1
     fi
-    
+
     # Confirm video stream is DivX 3/5
-    if [ "$ID_VIDEO_CODEC" != ffodivx -a "$ID_VIDEO_CODEC" != ffdivx ]; then
-        echo "failure: \`$1' video stream is not DivX format: $ID_VIDEO_CODEC" >&2
-        let failed=1
+    if [ "$ID_VIDEO_CODEC" != $VIDCODEC_DIVX5 -a "$ID_VIDEO_CODEC" != $VIDCODEC_DIVX3 ]; then
+        echo "$PROGNAME: failure: \`$1' video stream is not DivX format: $ID_VIDEO_CODEC" >&2
+        failed=1
     fi
-    
+
     # Confirm video bitrate does not exceed 4Mbps
     if [ $ID_VIDEO_BITRATE -gt 4000000 ]; then
-        echo "failure: \`$1' video bitrate exceeds 4Mbps: $ID_VIDEO_BITRATE" >&2
-        let failed=1
+        echo "$PROGNAME: failure: \`$1' video bitrate exceeds 4Mbps: $ID_VIDEO_BITRATE" >&2
+        failed=1
     fi
-    
+
     # Confirm video pixel width does not exceed 720
     if [ $ID_VIDEO_WIDTH -gt 720 ]; then
-        echo "failure: \`$1' video pixel width exceeds 720: $ID_VIDEO_WIDTH" >&2
-        let failed=1
+        echo "$PROGNAME: failure: \`$1' video pixel width exceeds 720: $ID_VIDEO_WIDTH" >&2
+        failed=1
     fi
-    
+
     # Confirm frame rate does not exceed 30fps
-    if [ `expr $ID_VIDEO_FPS \<= 30` -ne 1 ]; then
-        echo "failure: \`$1' frame rate exceeds 30fps: $ID_VIDEO_FPS" >&2
-        let failed=1
+    bc_run_cmds "z = 0; if($ID_VIDEO_FPS <= 30) { z = 1; }; z"
+    bc_read_result fps_le_30
+    if [ $fps_le_30 -ne 1 ]; then
+        echo "$PROGNAME: failure: \`$1' frame rate exceeds 30fps: $ID_VIDEO_FPS" >&2
+        failed=1
     fi
-    
+
     # Video pixel height check
-    if [ `expr $ID_VIDEO_FPS \> 25.000` -eq 1 ]; then
+    bc_run_cmds "z = 0; if($ID_VIDEO_FPS > 25) { z = 1; }; z"
+    bc_read_result fps_gt_25
+    if [ $fps_gt_25 -eq 1 ]; then
         # Must not exceed 480 if 25 < fps <= 30 (NTSC)
         if [ $ID_VIDEO_HEIGHT -gt 480 ]; then
-            echo "failure: \`$1' video pixel height exceeds 480 for NTSC mode: $ID_VIDEO_HEIGHT" >&2
-            let failed=1
+            echo "$PROGNAME: failure: \`$1' video pixel height exceeds 480 for NTSC mode: $ID_VIDEO_HEIGHT" >&2
+            failed=1
         fi
     else
         # Must not exceed 576 if fps <= 25 (PAL)
         if [ $ID_VIDEO_HEIGHT -gt 576 ]; then
-            echo "failure: \`$1' video pixel height exceeds 576 for PAL mode: $ID_VIDEO_HEIGHT" >&2
-            let failed=1
+            echo "$PROGNAME: failure: \`$1' video pixel height exceeds 576 for PAL mode: $ID_VIDEO_HEIGHT" >&2
+            failed=1
         fi
     fi
-    
+
     # Check if audio stream format is recognised
-    if [ $ID_AUDIO_FORMAT -eq 80 ]; then
-        # MPEG-1 Layer II audio
-        # Additional check - bitrate must not exceed 256kbps 
-        # Panasonic NV-VP60 refuses to play back higher bitrates - audio ends up muted.
-        if [ $ID_AUDIO_BITRATE -gt 256000 ]; then
-            echo "failure: \`$1' audio is MPEG-1 Layer II and bitrate exceeds 256kbps: $ID_AUDIO_BITRATE" >&2
-            let failed=1
-        fi
-    elif [ $ID_AUDIO_FORMAT -eq 85 ]; then
-        # MPEG-1 Layer III audio
-        # No additional checks needed
-        true
-    elif [ $ID_AUDIO_FORMAT -eq 8192 ]; then
-        # Dolby AC-3 audio
-        # No additional checks needed
-        true
-    else
+    if [ $ID_AUDIO_FORMAT -ne $AUDF_MPEG1_LAYER_II \
+            -a $ID_AUDIO_FORMAT -ne $AUDF_MPEG1_LAYER_III \
+            -a $ID_AUDIO_FORMAT -ne $AUDF_DOLBY_AC3 ]; then
         # Unrecognised audio format
-        echo "failure: \`$1' audio format is unrecognised: $ID_AUDIO_FORMAT ($ID_AUDIO_CODEC)" >&2
-        let failed=1
+        echo "$PROGNAME: failure: \`$1' audio format is unrecognised: $ID_AUDIO_FORMAT ($ID_AUDIO_CODEC)" >&2
+        failed=1
     fi
-    
+
     # Warn if aspect ratio is missing
-    if [ `expr "$ID_VIDEO_ASPECT" \= 0.0` -eq 1 ]; then
-        echo "warning: \`$1' does not have a video aspect ratio specified" >&2
+    bc_run_cmds "z = 0; if($ID_VIDEO_ASPECT == 0) { z = 1; }; z"
+    bc_read_result aspect_is_missing
+    if [ $aspect_is_missing -eq 1 ]; then
+        echo "$PROGNAME: warning: \`$1' does not have a video aspect ratio specified. DivX-HT players will assume square pixels which may be incorrect." >&2
     fi
 
     # Check if DivX MPEG-4 stream contains bidirectional predictive
     # frames (B-frames); the Panasonic NV-VP60 will not decode these
-    # frames and will skip over them, causing jerky motion in playback. 
-    # 
+    # frames and will skip over them, causing jerky motion in playback.
+    #
     # MPlayer produces a warning message when they are encountered, and
     # claims that they are not part of the DivX specification. The only
     # way we can detect these frames is to play back a brief portion of
     # the movie and monitor MPlayer's diagnostic output.
-    #
-    # The search string may need to be updated if the message changes.
-    # The below message is current for MPlayer 1.0rc4.
     if mplayer -vo null -ao null -frames 1 -benchmark -quiet "$1" 2>&1 \
-        | grep -q "Invalid and inefficient vfw-avi packed B frames detected"; then
-        echo "failure: \`$1' contains B-type frames and must be re-encoded" >&2
-        #echo "   (this will cause playback issues on the Panasonic NV-VP60)" >&2
-        let failed=1
+        | grep -q "$MPLAYER_WARN_BFRAMES_TEXT"; then
+        echo "$PROGNAME: failure: \`$1' contains B-type frames and must be re-encoded" >&2
+        failed=1
     fi
 
     # Check if OpenDML index would cause problems
-    file_size=`wc -c "$1"| sed 's/^[[:blank:]]*\([0-9]\+\).*$/\1/'`
-    if [ `expr $file_size \>= 1073741824` -eq 1 ]; then
+    file_size=`wc -c "$1" | sed 's/^[[:blank:]]*\([0-9]\+\).*$/\1/'`
+    bc_run_cmds "z = 0; if($file_size > 1073741824) { z = 1; }; z"
+    bc_read_result file_exceeds_1_gigabyte
+    if [ $file_exceeds_1_gigabyte -eq 1 ]; then
         # If file is >= 1GB, it must not contain an OpenDML index,
         # otherwise playback on the Panasonic NV-VP60 will experience
         # major problems when the 1GB boundary is trangressed (A-V
@@ -207,26 +322,28 @@ divxht_test() {
         #
         # Scan first 8kB of AVI file for a "dmlh" chunk (OpenDML header)
         if dd if="$1" bs=8192 count=1 2>/dev/null | strings -a -T binary | grep -q odmldmlh; then
-            echo "failure: \`$1' exceeds 1GB and contains an OpenDML index" >&2
-            #echo "  (this will cause playback issues on the Panasonic NV-VP60)" >&2
-            let failed=1
+            echo "$PROGNAME: failure: \`$1' exceeds 1GB and contains an OpenDML index" >&2
+            failed=1
         fi
     fi
-    
+
+    unset fps_le_30 fps_gt_25 file_exceeds_1_gigabyte aspect_is_missing
     return $failed
 }
 
-if [ $# -eq 0 ]; then
-    echo "Usage: $0 AVIFILE..."
-    echo "Checks a list of AVI files for DivX Home Theatre compliance"
-    echo "    (requires \`mplayer' program to be in system path)"
-    exit 1
-fi
+while getopts "h" opt; do
+    case $opt in
+        'h') print_help; exit 0;;
+        '?') print_try_help; exit 1;;
+    esac
+done
+shift $(($OPTIND-1))
 
-if ! which mplayer >/dev/null 2>&1; then
-    echo "error: This script requires the program \`mplayer' to be in the system path"
-    exit 1
-fi
+assert_have_program bc mplayer mkfifo
+
+# List of bc session variables (POSIX bc only permits single-letter names):
+#   z   Used to temporarily store the result of conditionals
+bc_start
 
 exit_status=0
 for file; do
@@ -234,5 +351,7 @@ for file; do
         exit_status=1
     fi
 done
+
+bc_end
 
 exit $exit_status
